# Generated by Django 5.0.2 on 2024-03-08 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Anomaly Info',
                'verbose_name_plural': 'Anomaly Infos',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NTN',
            fields=[
                ('ntn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'NTN',
                'verbose_name_plural': 'NTNs',
            },
        ),
        migrations.CreateModel(
            name='MissingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices', models.CharField(max_length=256, validators=[django.core.validators.int_list_validator])),
                ('date', models.DateField()),
                ('ntn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.ntn')),
            ],
            options={
                'verbose_name': 'Missing Invoice',
                'verbose_name_plural': 'Missing Invoices',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('srb_invoice_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('pos_id', models.IntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('invoice_no', models.CharField(max_length=256, null=True)),
                ('rate_value', models.FloatField(null=True)),
                ('sales_value', models.FloatField()),
                ('sales_tax', models.FloatField()),
                ('consumer_name', models.CharField(max_length=256, null=True)),
                ('consumer_ntn', models.CharField(blank=True, max_length=256, null=True)),
                ('consumer_address', models.CharField(max_length=256, null=True)),
                ('tariff_code', models.CharField(blank=True, max_length=256, null=True)),
                ('extra_info', models.CharField(max_length=256, null=True)),
                ('pos_user', models.CharField(max_length=256, null=True)),
                ('pos_pass', models.CharField(max_length=256, null=True)),
                ('is_active', models.BooleanField()),
                ('created_date_time', models.DateTimeField()),
                ('invoice_type', models.CharField(blank=True, max_length=256, null=True)),
                ('consider_for_annex', models.IntegerField(null=True)),
                ('anomaly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.anomalyinfo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.location')),
                ('ntn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.ntn')),
            ],
            options={
                'verbose_name': 'Anomaly',
                'verbose_name_plural': 'Anomalies',
            },
        ),
    ]
