# Generated by Django 5.0.3 on 2024-03-22 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='missinginvoice',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missinginvoice',
            name='pos_id',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='sales_tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='sales_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='missinginvoice',
            name='invoices',
            field=models.CharField(max_length=10000, validators=[django.core.validators.int_list_validator]),
        ),
    ]
